name: qandang
description: Smart Livestock Monitoring System for Goat Farming
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  mobile_scanner: ^5.0.0
  vibration: ^1.9.0
  fl_chart: ^0.70.2
  sqflite: ^2.4.1
  path: 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#fdfaf5"
  image: assets/images/logo.png
  ios: true
  android_12:
    image: assets/images/logo.png
    color: "#fdfaf5"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

